### ISSUE TITLE
Need support for alternateviews [sf#15]

### ISSUE THREAD

**Issue by nilnull** [nilnull/AIM#14]
**Reported by srikanthaj on 2018-02-02 03:40 UTC**
Please add capability to send mailmessages with alternatevies, it helps is embed inline images with Linkedresources.

**Comment by nilnull** [comment]
**Commented by srikanthaj on 2018-02-02 03:41 UTC**
I mean bring this capaility:
https://stackoverflow.com/a/11000938/5702399

**Comment by nilnull** [comment]
**Commented by srikanthaj on 2018-02-02 07:40 UTC**
I think, I kind of fixed this. Let me know if any assistance is needed on this front.

**Comment by nilnull** [comment]
**Commented by nilnull on 2018-04-23 15:05 UTC**
Hi Great and thanks, would appriciate if you can help us. and provide us your changeset

**Comment by UDTDR** [comment]
push. thanks

best regards
