### ISSUE TITLE
Cannot use package on .NET 7 VS 2022

### ISSUE THREAD

**Issue by kofifus** [nilnull/AIM#35]
I installed the package using package manager "NuGet\Install-Package AIM -Version 1.1.1" and can that it is installed

However trying `using AegisImplicitMail;` gets me
> he type or namespace name 'AegisImplicitMail' could not be found

What's wrong here ?

**Comment by ds600** [comment]
I am in front of the same problem, did you find a solution?

EDIT:
Alright, I just had to downgrade to 1.1.0 I guess
